name: 🐛 Bug Report
description: Report a bug or unexpected behavior in Nebula.
body:
  - type: markdown
    attributes:
      value: |
        <h1 align="center">Nebula</h1>

        <div align="center">
          <a href="https://zen-browser.app/">
            <img width="80" alt="Zen Browser" src="https://github.com/user-attachments/assets/d6ab3ddf-6630-4062-92d0-22497d2a3f9a" />
          </a>
        </div>

        <p align="center"><em>Thank you for helping improve Nebula by reporting bugs!</em></p>

        > [!IMPORTANT]
        > - Use clear and descriptive titles.  
        > - Search existing issues to avoid duplicates.  
        > - For feature/enhancement requests, use the appropriate template.  
        > - Fill out all required fields for better issue tracking.  
        > - Include screenshots or recordings when possible.  
        > - Nebula does not support specific Zen Mods. Please test without them first.

  - type: checkboxes
    id: prechecks
    attributes:
      label: ✅ Before You Submit
      description: Confirm these points before filing your report.
      options:
        - label: I have read and understood the important notes above.
          required: true
        - label: I have tested this without any Zen Mods enabled.
          required: true
        - label: This is a bug report, not a feature request.
          required: true
        - label: I can confirm this issue only occurs with Nebula enabled.
          required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the bug in detail. Include what you expected to happen.
      placeholder: I encountered a bug where...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Help us reproduce the issue. List steps in order.
      placeholder: |
        1. Open Zen Browser  
        2. Enable Compact Mode  
        3. Click on the tab switcher  
        4. Observe the glitch
    validations:
      required: false

  - type: textarea
    id: media
    attributes:
      label: Screenshots / Videos
      description: Attach screenshots or recordings to help illustrate the problem.

  - type: input
    id: nebula-version
    attributes:
      label: Nebula Version
      description: The version of Nebula you're using (see the About section).
      placeholder: e.g., v3.0.0
    validations:
      required: true

  - type: input
    id: zen-version
    attributes:
      label: Zen Browser Version
      description: The version of Zen Browser you're running.
      placeholder: e.g., 1.13.2b
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Select all platforms where the issue occurs.
      multiple: true
      options:
        - Windows - x64
        - Windows - aarch64
        - macOS - Intel
        - macOS - Apple Silicon
        - Linux (AppImage)
        - Linux (Flatpak)
        - Linux (Tarball)
        - Other
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Affected Component
      description: What part of Nebula is affected?
      options:
        - Bookmarks
        - Compact Mode
        - Customizable UI / Toolbars
        - Extensions
        - Glance
        - Miniplayer
        - Mods / Themes
        - Performance
        - Settings
        - Split View
        - Tab Folders
        - Tab Unloading
        - Tabs
        - URL Bar
        - Workspaces
        - Other
    validations:
      required: true
