name: Bug Report
description: File a bug report for Nebula
body:
  - type: markdown
    attributes:
      value: |
        <h1 align="center">Nebula</h1>
<div align="center">
    <a href="https://zen-browser.app/">
        <img width="120" alt="zen-badge-dark" src="https://github.com/user-attachments/assets/d6ab3ddf-6630-4062-92d0-22497d2a3f9a" />
    </a>
</div>
        
        <p align="center"><em>Thank you for filing a bug report!</em></p>

        > [!IMPORTANT]
        > - Please provide descriptive titles. Bad titles do more harm than good.
        > - Please search existing issues to avoid creating duplicates.
        > - For enhancement requests, please use the other issue template
        > - Please fill out the template below to the best of your ability.
        > - Please describe the issue as much as possible and provide steps to reproduce it along with visual aids if possible.
        > - We can't make Nebula support specific Zen Mods if that's what you're asking for.

  # ... (the rest of your template follows as-is)

  - type: checkboxes
    id: captchas
    attributes:
      label: Preliminary Checks
      description: Please confirm the following before submitting a bug report. This helps us triage and resolve issues more efficiently.
      options:
        - label: I have read and understood the important section above.
          required: true
        - label: I have tried replicating this issue without any Zen Mods enabled
          required: true
        - label: I am not filing an enhancement (Feature) request.
          required: true
        - label: I have checked that this issue cant be reproduced without Nebula.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug clearly and concisely.
      placeholder: Tell us what you see!
    validations:
      required: true
      
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Steps to reproduce
      description: If you can, then please provide numbered steps to reproduce this issue so developers can replicate them easily.
    validations:
      required: false
      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots and videos
      description: |
        If applicable, add screenshots or videos to help explain your problem.
        
  - type: input
    id: nebula-version
    attributes:
      label: Nebula Version
      description: What version of Nebula are you using?
      placeholder: e.g., v3.0.0
    validations:
      required: true

  - type: input
    id: zen-version
    attributes:
      label: Zen Browser Version
      description: What version of Zen Browser are you using?
      placeholder: e.g., 1.13.2b
    validations:
      required: true

      
  - type: dropdown
    id: platform
    attributes:
      label: What platform are you seeing the problem on?
      multiple: true
      options:
        - Linux (AppImage)
        - Linux (Flatpak)
        - Linux (Tarball)
        - macOS - aarch64 (Apple Silicon)
        - macOS - Intel
        - Windows - aarch64
        - Windows - x64
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: What component is this issue related to?
      options:
        - Other
        - Bookmarks
        - Compact Mode
        - Customizable UI / Toolbars
        - Extensions
        - Glance
        - Miniplayer
        - Other Mods / Themes
        - Performance
        - Settings
        - Split View
        - Tab Folders
        - Tab unloading
        - Tabs
        - URL Bar
        - Workspaces
    validations:
      required: true
